### ISSUE TITLE
Is this really working for ES 5.2.0?

### ISSUE THREAD

**Issue by anuriq** [vvanholl/elasticsearch-consul-discovery#1]
Hi Vincent.

First, let me thank you for your efforts, really appreciate your work.

Recently I've been trying to build ES cluster using this plugin. Unfortunately couldn't make it work.
I have 3 ES servers with config:
```
---
cluster.name: svc-local
node.name: esXX-el7
path.conf: "/etc/elasticsearch"
path.data: "/var/lib/elasticsearch"
path.logs: "/var/log/elasticsearch"
network.host: _site_,_local_
discovery.zen.minimum_master_nodes: 2
discovery.consul.service-names:
- svc-elasticsearch-local
```

During startup, these nodes seem to not use consul discovery at all. Here is the log:
```
[2017-02-16T12:15:39,421][INFO ][o.e.n.Node               ] [es01-el7] initialized
[2017-02-16T12:15:39,421][INFO ][o.e.n.Node               ] [es01-el7] starting ...
[2017-02-16T12:15:39,588][INFO ][o.e.t.TransportService   ] [es01-el7] publish_address {10.123.44.217:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}, {10.123.44.217:9300}
[2017-02-16T12:15:39,596][INFO ][o.e.b.BootstrapChecks    ] [es01-el7] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-02-16T12:16:09,622][WARN ][o.e.n.Node               ] [es01-el7] timed out while waiting for initial discovery state - timeout: 30s
[2017-02-16T12:16:09,633][INFO ][o.e.h.HttpServer         ] [es01-el7] publish_address {10.123.44.217:9200}, bound_addresses {[::1]:9200}, {127.0.0.1:9200}, {10.123.44.217:9200}
[2017-02-16T12:16:09,633][INFO ][o.e.n.Node               ] [es01-el7] started
[2017-02-16T12:16:10,449][DEBUG][o.e.a.a.c.s.TransportClusterStateAction] [es01-el7] no known master node, scheduling a retry
[2017-02-16T12:16:20,112][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [es01-el7] no known master node, scheduling a retry
[2017-02-16T12:16:30,109][DEBUG][o.e.a.a.c.s.TransportClusterStateAction] [es01-el7] no known master node, scheduling a retry
[2017-02-16T12:16:40,124][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [es01-el7] no known master node, scheduling a retry
[2017-02-16T12:16:40,451][DEBUG][o.e.a.a.c.s.TransportClusterStateAction] [es01-el7] timed out while retrying [cluster:monitor/state] after failure (timeout [30s])
[2017-02-16T12:16:40,452][WARN ][r.suppressed             ] path: /_cat/master, params: {}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:211) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:307) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:237) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$NotifyTimeout.run(ClusterService.java:1157) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[2017-02-16T12:16:50,113][DEBUG][o.e.a.a.c.h.TransportClusterHealthAction] [es01-el7] timed out while retrying [cluster:monitor/health] after failure (timeout [30s])
[2017-02-16T12:16:50,114][WARN ][r.suppressed             ] path: /_cluster/health, params: {level=indices}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:211) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:307) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:237) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$NotifyTimeout.run(ClusterService.java:1157) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[2017-02-16T12:16:50,119][DEBUG][o.e.a.a.c.s.TransportClusterStateAction] [es01-el7] no known master node, scheduling a retry
[2017-02-16T12:17:00,110][DEBUG][o.e.a.a.c.s.TransportClusterStateAction] [es01-el7] timed out while retrying [cluster:monitor/state] after failure (timeout [30s])
[2017-02-16T12:17:00,111][WARN ][r.suppressed             ] path: /_cat/master, params: {}
org.elasticsearch.discovery.MasterNotDiscoveredException: null
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$4.onTimeout(TransportMasterNodeAction.java:211) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:307) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:237) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.cluster.service.ClusterService$NotifyTimeout.run(ClusterService.java:1157) [elasticsearch-5.2.0.jar:5.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:527) [elasticsearch-5.2.0.jar:5.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by vvanholl** [comment]
Hi @anuriq,

YES, this works for 5.2.0 because I am using it :)

Here is a sample configuration wich runs on my testing cluster: 

bootstrap.memory_lock: true
cluster.name: elastic
discovery.consul.service-names:
- elasticsearch_node
discovery.type: consul
discovery.zen.minimum_master_nodes: 2
gateway.expected_nodes: 2
gateway.recover_after_time: 5m
network.host: 0.0.0.0
node.name: 8f0ddc9819ba

discovery.type is missing. You have to fix this first

**Comment by anuriq** [comment]
thanks, @vvanholl 
I'll check and let you know. Is this available in docs, btw?

**Comment by vvanholl** [comment]
Hi @anuriq,

Is your problem solved now ?

In fact this is present in doc :
discovery:
  type: consul

**Comment by anuriq** [comment]
yes it is working. thank you!
